name: ciPipeline
on:
  push: 
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
        - name: checkout code
          run: echo "checkout code"
        - name: build completed
          run: echo "build completed"

  test:
    runs-on: ubuntu-latest
    steps: 
        - name: test completed
          run: echo "test completed"
  
  deploy:
    runs-on: ubuntu-latest
    steps: 
        - name: deploy completed
          run: echo "deploy completed"