name: ciPipeline
on:
  push: 
    branches:
      - main
      - development
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
        - name: checkout code
          run: echo "checkout code"
        - name: build completed
          run: echo "build completed"

  test:
    needs: build
    runs-on: ubuntu-latest
    steps: 
        - name: test completed
          run: echo "test completed"
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps: 
        - name: deploy completed
          run: echo "deploy completed"
  
  create_file:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
       - name: file creation
         run: echo "Hello Durgarao this is new file" > myfile.txt
       - name: upload artifact
         uses: actions/upload-artifact@v4
         with:
           name: my-artifact
           path: myfile.txt
  list_files:
    needs: create_file
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: List all files
        run: ls -l
  read_file:
    needs: list_files
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: read files
        run: cat myfile.txt
  deploy-only:
    if: github.ref == 'refs/heads/main'
    needs: read_file
    runs-on: ubuntu-server
    steps:
      - name: deploy-to-prod
        run: echo "Deploy to prod only"
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        run: |
          echo "Repo: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "OS: ${{ runner.os }}"
